---
- name: config - Setup monitrc
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 0700
  notify: restart monit
  when: ansible_os_family == "debian"

- name: config - Setup monitrc
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    owner: root
    group: root
    mode: 0700
  notify: restart monit
  when: ansible_os_family == "RedHat"

- name: config - Setup webinterface
  template:
    src: webinterface.j2
    dest: /etc/monit/conf.d/webinterface
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: ansible_os_family == "debian"

- name: config - Setup webinterface
  template:
    src: webinterface.j2
    dest: /etc/monit.d/webinterface
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: ansible_os_family == "RedHat"

- name: config - Setup mail alerts
  template:
    src: mail.j2
    dest: /etc/monit/conf.d/mail
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled
  when: ansible_os_family == "debian"

- name: create dir
  file: path=/var/lib/monit mode=0755 state=directory
