---
- include: installation.packages.yml
  when: nginx_installation_type == "packages"
- include: remove-defaults.yml
  when: not keep_only_specified
- include: remove-extras.yml
  when: keep_only_specified
- include: remove-unwanted.yml
- include: configuration.yml
- include: start.yml
