- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - libgeos-c1
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_ext_postgis_version}}"
  notify:
    - restart postgresql
