---
# RedHat tasks file for PostgreSQL
- name: Install libselinux if needed
  yum: name=libselinux-python state=present
  when: ansible_selinux == false

- include: install.yml
  tags: [postgresql, postgresql-install]

- include: extensions.yml
  tags: [postgresql, postgresql-extensions]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: databases.yml
  tags: [postgresql, postgresql-databases]

- include: users.yml
  tags: [postgresql, postgresql-users]

